phpCAS: Initialization
Initialization
[User interface]
Functions
phpCAS::client ($server_version, $server_hostname, $server_port, $server_uri, $start_session=true)
phpCAS::proxy ($server_version, $server_hostname, $server_port, $server_uri, $start_session=true)
Function Documentation
phpCAS::client ($ server_version, $ server_hostname, $ server_port, $ server_uri, $ start_session = true) [inherited]
phpCAS client initializer.
Note:
Only one of the phpCAS::client() and phpCAS::proxy functions should be called, only once, and before all other methods (except phpCAS::getVersion() and phpCAS::setDebug()).
Parameters:
$server_version the version of the CAS server
$server_hostname the hostname of the CAS server
$server_port the port the CAS server is running on
$server_uri the URI the CAS server is responding on
$start_session Have phpCAS start PHP sessions (default true)
Returns:
a newly created CASClient object
Examples:
example_custom_urls.php, example_gateway.php, example_html.php, example_lang.php, example_service.php, example_session_service.php, and example_simple.php.
Definition at line 366 of file CAS.php.
References phpCAS::backtrace(), phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::proxy ($ server_version, $ server_hostname, $ server_port, $ server_uri, $ start_session = true) [inherited]
phpCAS proxy initializer.
Note:
Only one of the phpCAS::client() and phpCAS::proxy functions should be called, only once, and before all other methods (except phpCAS::getVersion() and phpCAS::setDebug()).
Parameters:
$server_version the version of the CAS server
$server_hostname the hostname of the CAS server
$server_port the port the CAS server is running on
$server_uri the URI the CAS server is responding on
$start_session Have phpCAS start PHP sessions (default true)
Returns:
a newly created CASClient object
Examples:
example_db.php, example_file.php, example_proxy.php, example_proxy2.php, and example_session_proxy.php.
Definition at line 415 of file CAS.php.
References phpCAS::backtrace(), phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().