# Lab 6: Warm-up Questions
# Insert into webct table
# id | qtype | title | image | question | answers | category
INSERT INTO webct VALUES(2050,'P','Discrete-Time Convolution','','The convolution of two impulses, <tt>&delta;[n-3]*&delta;[n-5]</tt>. Explain the location of the impulses.', 1, 'Warm-up07');
INSERT INTO webct VALUES(2051,'P','Discrete-Time Convolution','','Convolve two rectangular pulses: one with an amplitude of 2 and a length of 9, the other with an amplitude of 3 and a length of 4. Make a sketch of the output signal, showing its length and its maximum amplitude.', 0, 'Warm-up07');
INSERT INTO webct VALUES(2052,'P','Discrete-Time Convolution','','State the <i>length</i> of the convolved rectangles.', 1, 'Warm-up07');
INSERT INTO webct VALUES(2053,'P','Discrete-Time Convolution','','State the <i>maximum amplitude</i> of the convolved rectangles.', 1, 'Warm-up07');
INSERT INTO webct VALUES(2054,'P','','','Set the input signal to be a sinusoid that is missing 3 out of every 4 values:<pre class="MATLAB">sin(pi/23*(1:40)) .* (rem(1:40,4)==0)</pre>Select the <b>User Input</b> type within <b>Get x[n]</b> to do this.', 0, 'Warm-up07');
INSERT INTO webct VALUES(2055,'P','','','Set the impulse response to be<pre class="ITS_Equation">h[n] = 0.25&delta;[n] + 0.5&delta;[n-1] + 0.75&delta;[n-2] + &delta;[n-3] + 0.75&delta;[n-4] + 0.5&delta;[n-5] + 0.25&delta;[n-6]</pre>Once again, select <b>User Input</b> within <b>Get h[n]</b>; and enter the appropriate MATLAB code. Use the GUI to view the output signal <tt>y[n]</tt> and explain how it is related to <tt>x[n]</tt>.', 1, 'Warm-up07');
INSERT INTO webct VALUES(2056,'P','','','Now do the same filtering with MATLAB code. Using the same filter as in part (b), define the filter coefficient vector <tt>bb</tt> for this FIR filter and then use it in <tt>firfilt</tt> to process a signal whose mathematical definition is:<p><center><img src="/cgi-bin/mimetex.exe?\\begin{array} x[n]=\\begin{cases} cos(\\pi n/23) & \\text{ n=0,4,8,12, ...} \\\\ 0 & \\text{ elsewhere}\\end{cases}\\end{array}" alt="o"></center><p>We can create a vector <tt>xx</tt> with the signal <tt>x[n]</tt> by using MATLAB code similar to part (a)<pre class="MATLAB">nn = 0:(L-1);<br>xx = ?????; <span class="ML_comment">%<-- use the definition of x[n]</span><br>xx = xx .* (rem(nn,4)?????); <span class="ML_comment">%- zero out elements other than every fourth</span></pre>Fill in the missing MATLAB code with the &ldquo;remainder trick&rdquo; that makes a signal with zeros except for indices that are multiples of four.<p>For the filtering in the next part, make a signal with 10 nonzero values, i.e., a total length of 40 points.', 1, 'Warm-up07');
INSERT INTO webct VALUES(2057,'P','','','To illustrate the filtering action of the FIR filter, you must make a plot of the input signal and output signal together using <tt>subplot</tt> as shown in Section 2.2. The plotting range for both signals should be set equal to the length of the input signal, even though the output signal is longer.', 0, 'Warm-up07');
INSERT INTO webct VALUES(2058,'P','','','Explain the filtering action of the FIR interpolation filter by comparing the plots in the previous part. Two features should be noted: the output is shifted with respect to the input; and the output signal has filled in &ldquo;interpolated&rdquo; values in between the original input values.', 1, 'Warm-up07');
INSERT INTO webct VALUES(2059,'P','','','Complete the MATLAB code to load and view the CFA output.', 1, 'Warm-up07');
INSERT INTO webct VALUES(2060,'P','','','Load in the image <tt>echart.mat</tt> (from the <i>SP-First</i> Toolbox) with the <tt>load</tt> command. This will create the variable echart whose size is <tt>257 x 256</tt>. We can filter all the rows of the image at once with the <tt>conv2()</tt> function. To filter the image in the horizontal direction using a first-difference filter, we form a <i>row</i> vector of filter coefficients and use the following MATLAB statements:<pre class="MATLAB">bavg = ones(1,11)/11;<br>yyh = conv2(echart, bdiffh);</pre>In other words, the filter coefficients in <tt>bdiffh</tt> for the first-difference filter are stored in a <i>row</i> vector and will cause <tt>conv2()</tt> to filter all rows in the <i>horizontal</i> direction. Display the input image <tt>echart</tt> and the output image <tt>yyh</tt> on the screen at the same time.<sup><span class="footer" onmouseover="footer(this,\'If you use <tt>imshow</tt> to display the image you must scale the values to be in the interval [0,1]\',1)" onmouseout="footer(this,\'\',0)">5</span></sup> Compare the two images and give a qualitative description of what you see.', 1, 'Warm-up07');
INSERT INTO webct VALUES(2061,'P','','','Now filter the &ldquo;eye-chart&rdquo; image echart in the <i>vertical</i> direction with a first-difference filter to produce the image <tt>yh</tt>. This is done by transposing the <tt>bdiffh</tt> filter coefficients and calling <tt>yyh = conv2(echart,bdiffh&rsquo;,&rsquo;same&rsquo;)</tt> with a column vector of filter coefficients. Display the image <tt>yyv</tt> on the screen and describe in words how the output image compares to the input.', 1, 'Warm-up07');


