# Lab 8: Warm-up Questions
# Insert into webct table
# id | qtype | title | image | question | answers | category
INSERT INTO webct VALUES(2074,'P','Pre-emphasis Filter','','Define a pre-emphasis filter as <tt>H(z)=1-0.99z<sup>-1</sup></tt>, which is very close to a first-difference filter.  Make a plot of its frequency response (magnitude only) by using <tt>freqz</tt> and <tt>plot</tt>. Notice what type of filter this is, i.e., LPF, HPF, or BPF.', 1, 'Warm-up09');
INSERT INTO webct VALUES(2075,'P','Pre-emphasis Filter','','Apply <tt>H(z)</tt> to a speech signal, e.g., <tt>catsdogs.wav</tt>.  To show the effect of the filter, make spectrograms of the input signal and the output signal.  Describe features in the spectrograms that confirm the frequency response behavior of the pre-emphasis filter.', 1, 'Warm-up09');
INSERT INTO webct VALUES(2076,'P','Pre-emphasis Filter','','Listen to the speech signal before and after pre-emphasis. Can you hear the difference in high-frequency spectral content?   It might not be easy unless you have high-quality headphones.', 1, 'Warm-up09');
INSERT INTO webct VALUES(2077,'P','Envelopes via Full-Wave Rectification and Lowpass Filtering','','Generate an amplitude-modulated sinusoid using <pre class="ITS_Equation">b(t) = (1 + &beta;cos(2&pi;f<sub>1</sub>t))cos(2&pi;f<sub>2</sub>t)</pre>Pick <tt>f<sub>1</sub>=9</tt> Hz, <tt>f<sub>2</sub>=867</tt> Hz, and <tt>&beta;=0.4</tt>.  Use a sampling rate of <tt>f<sub>s</sub>=8000</tt> Hz to create the vector of signal values in MATLAB; call it <tt>bb.</tt> Plot the signal vs. time over an interval of about 0.3 s. Point out the feature of th plot that is the envelope of the signal.', 0, 'Warm-up09');
INSERT INTO webct VALUES(2078,'P','Envelopes via Full-Wave Rectification and Lowpass Filtering','','In MATLAB take the magnitude of <tt>bb</tt> and plot the magnitude versus time <tt>t</tt>. Once again, point out the feature of the signal that is the envelope.', 0, 'Warm-up09');
INSERT INTO webct VALUES(2079,'P','Envelopes via Full-Wave Rectification and Lowpass Filtering','','Zoom in to a short time interval of 0.05 s, or less, to see the detailed high-frequency nature of the signal.', 0, 'Warm-up09');
INSERT INTO webct VALUES(2080,'P','Envelopes via Full-Wave Rectification and Lowpass Filtering','','Since lowpass filters are well-known for making signals smooth, we need a LPF that will <i>pass</i> the frequency range where we expect to find the  envelope signal, and <i>reject</i> the frequency range where the high frequency component lies.<p>Use the <tt><b>filterdesign</b></tt> GUI to create a LPF with its cutoff frequency at an appropriately chosen cutoff frequency.  Try different filter orders, but something less than <tt>M=30</tt> should work fine.  Since the   <tt><b>filterdesign</b></tt>  can take inputs that are analog frequencies, the cutoff frequency can be chosen directly in hertz. Use the GUI&rsquo;s plot of the frequency response to verify the correct locations of the passband and stopband.<p>LPF&rsquo;s cutoff frequency in hertz?', 1, 'Warm-up09');
INSERT INTO webct VALUES(2081,'P','Envelopes via Full-Wave Rectification and Lowpass Filtering','','Export the filter coefficients in order to use them with the <tt>firfilt</tt> function to process the magnitude signal <tt>|b(t)|</tt>.   Note that the GUI will use the default names <tt>num</tt> and <tt>den</tt> when exporting. Make a plot of the output signal from the LPF, which is the filtered magnitude.  Compare the result to the expected shape of the envelope.  Point out similarities and differences; there might be a fixed scaling between the two plots.  Explain why the beginning and end of the output signal are unlike the rest.', 1, 'Warm-up09');
