# Lab 5: Warm-up Questions
# Insert into webct table
# id | qtype | title | image | question | answers | category
INSERT INTO webct VALUES(2034,'MC','Sampling theorem','','Set the input frequency to <tt>&fnof;<sub>0</sub>=11.9</tt> Hz. Determine the minimum sampling rate <tt>&fnof;s</tt> so that no aliasing occurs.  The units of <tt>&fnof;<sub>s</sub></tt> are samples per second.  The <tt>con2dis</tt> GUI allows you to change <tt>&fnof;<sub>s</sub></tt> with a slider, so you can experiment with different values, but the GUI shows integers. Try this with two different phases, <tt>&phi;=0</tt> and <tt>&phi;=2</tt> rads, and note the different outputs. Once you learn the answer, you must justify your response by citing a theorem or property about sampling.', 4, 'Warm-up05');
INSERT INTO webct VALUES(2035,'MC','','','Set the input frequency to <tt>&fnof;<sub>0</sub>=9</tt> Hz and the input phase to <tt>&phi; = 2</tt> rads. Determine the locations of the spectral lines in the spectrum of the discrete-time signal (middle plot of the bottom row) when the sampling rate  is <tt>&fnof;s=20</tt> Hz.  Calculate <img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> for the two spectral lines that lie in the range <tt>-&pi;&le;<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega">&le;&pi;</tt>. Explain how you calculated the two values for <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></tt>, i.e., give the formula for <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></tt> in terms of <tt>&fnof;<sub>0</sub></tt> and <tt>&fnof;<sub>s</sub></tt>.', 4, 'Warm-up05');
INSERT INTO webct VALUES(2036,'MC','','','For the same parameters as the previous part, determine the complex amplitudes for the two spectral lines that lie in the range <tt>-&pi;&le;<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega">&le;&pi;</tt>; these are the blue lines in the middle plot of the bottom row. Give the magnitude and phase of both complex amplitudes, i.e., polar form. Explain how you get these.', 4, 'Warm-up05');
INSERT INTO webct VALUES(2037,'MC','','','<i>Aliasing:</i> Set the input frequency to <tt>&fnof;<sub>0</sub>=13</tt> Hz and the input phase is <tt>&phi;=2</tt> rads. Use the GUI to find the sampling rate  <tt>&fnof;s</tt> for which the output signal <tt>y(t)</tt> is DC, i.e.,  a constant. Using this <tt>&fnof;s</tt>, calculate <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega">=2&pi;(&fnof;<sub>0</sub>/&fnof;<sub>s</sub>)</tt>. Then explain how you get zero frequency from this value of <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></tt>.', 4, 'Warm-up05');
INSERT INTO webct VALUES(2038,'MC','','','<i>Aliasing:</i> Set the input frequency to <tt>&fnof;<sub>0</sub>=23</tt> Hz and the input phase to <tt>&phi;=2</tt> rads. Write down the formula for the output signal when  <tt>&fnof;<sub>s</sub>=20</tt> Hz.  Note: <tt>y(t)</tt> can be found in the GUI.', 4, 'Warm-up05');
INSERT INTO webct VALUES(2039,'MC','','','<i>Folding:</i> Set the input frequency to <tt>&fnof;<sub>0</sub>=17</tt> Hz and the input phase to <tt>&phi;=2</tt> rads. Write down the formula for the output signal when <tt>&fnof;<sub>s</sub>=20</tt> Hz.', 4, 'Warm-up05');
# Insert into webct table
# id | feedback | weight{n} | answer{n} | reason{n}
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4) VALUES(2034,0,'<tt>Slightly larger than &fnof;<sub>s</sub> = 5.8 Hz</tt>',0,'<tt>Slightly larger than &fnof;<sub>s</sub> = 0.8 Hz</tt>',0,'<tt>Slightly larger than &fnof;<sub>s</sub> = 25.9 Hz</tt>',100,'<tt>Slightly larger than &fnof;<sub>s</sub> = 23.8 Hz</tt>');
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4) VALUES(2035,0,'<tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 0.1&pi;</tt>',0,'<tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 1.7&pi;</tt>',100,'<tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 0.9&pi;</tt>',0,'<tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 1.8&pi;</tt>');
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4) VALUES(2036,100,'<tt>a<sub>k</sub> = 0.5e<sup>j2</sup></tt>',0,'<tt>a<sub>k</sub> = 0.5</tt>',0,'<tt>a<sub>k</sub> = e<sup>j2</sup></tt>',0,'<tt>a<sub>k</sub> = 0.5e<sup>j</sup></tt>');
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4) VALUES(2037,0,'<tt>&fnof;<sub>s</sub> = 20</tt>',100,'<tt>&fnof;<sub>s</sub> = 13</tt>',0,'<tt>&fnof;<sub>s</sub> = 10</tt>',0,'<tt>&fnof;<sub>s</sub> = 26</tt>');
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4) VALUES(2038,0,'<tt>y(t) = cos(2&pi;(23)t + 2)</tt>',0,'<tt>y(t) = cos(6&pi;t - 2)</tt>',0,'<tt>y(t) = cos(2&pi;(23)t - 2)</tt>',100,'<tt>y(t) = cos(6&pi;t + 2)</tt>');
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4) VALUES(2039,0,'<tt>y(t) = cos(2&pi;(23)t + 2)</tt>',100,'<tt>y(t) = cos(2&pi;(23)t - 2)</tt>',0,'<tt>y(t) = cos(6&pi;t + 2)</tt>',0,'<tt>y(t) = cos(6&pi;t - 2)</tt>');