# Lab 1: Warm-up Questions
# Insert into webct table
# id | qtype | title | image | question | answers | category
INSERT INTO webct VALUES(2001, 'P', '', '', 'Make sure that you understand the <b>colon</b> notation. In particular, explain in words what each of the following MATLAB statements will produce<pre>jkl = 0 : 6 <p>nnn = 2 : 4 : 17<p>mmm = 99 : -1 : 88<p>ttt = 2 : (1/9) : 4<p>tpi = pi * [ 0:0.1:2 ];</pre>', 1, 'Warm-up01');
INSERT INTO webct VALUES(2002, 'P', '', '', 'Extracting and/or inserting numbers in a vector is very easy to do. Consider the definition of <tt>xx</tt> in the first line:<pre>xx = [ zeros(1,3), linspace(0,1,5), ones(1,4) ]<p>xx(4:7)<p>size(xx)<p>length(xx)<p>xx(2:2:length(xx))</pre> Explain the results echoed from each of the last four lines of the above code.', 4, 'Warm-up01');
INSERT INTO webct VALUES(2003, 'P', '', '', 'Observe the result of the following two assignments, where <tt>xx</tt> was defined in part (b):<pre>yy = xx; yy(4:6) = exp(1)*(1:3)</pre> Now write a statement that will take the vector <tt>xx</tt> defined in part (b) and replace the even indexed elements (i.e., <tt>xx(2)</tt>, <tt>xx(4)</tt>, etc) with the constant &pi;<sup>e</sup>. <i>Use a vector replacement, not a loop.</i>', 1, 'Warm-up01');
INSERT INTO webct VALUES(2004, 'P', '', '', 'Experiment with vectors in MATLAB. Think of the vector as a list of numbers. Try the following:<pre>xk = cos( pi*(0:11)/4 ); <span class="ML_comment">%<-- comment: compute cosines</span></pre> Explain how the different values of cosine are stored in the vector <tt>xk</tt>. What is <tt>xk(1)</tt>? Is <tt>xk(0)</tt> defined? <p>NOTES: the semicolon at the end of a statement will suppress the echo to the screen. The text following the % is a comment; it may be omitted.', 1, 'Warm-up01');
INSERT INTO webct VALUES(2005, 'P', '', '', '(A taste of vectorization) Loops can be written in MATLAB, but they are <b>NOT</b> the most efficient way to get things done. It is better to <b>always avoid loops</b> and use the colon notation instead. The following code has a loop that computes values of the cosine function. (The index of <tt>yy()</tt> must start at 1.) Rewrite this computation without using the loop (follow the style in the previous part).<pre>yy = [ ]; <span class="ML_comment">%<-- initialize the yy vector to be empty</span> <p>for k=-50:50 <p>yy(k+51) = exp( -(k/30).*(k/30) ) <p>end <p>plot(yy)</pre></span> Explain why it is necessary to write <tt>yy(k+51)</tt>.', 1, 'Warm-up01');
INSERT INTO webct VALUES(2006, 'P', '', '', 'What happens if you use <tt>yy(k)</tt> instead?', 1, 'Warm-up01');
INSERT INTO webct VALUES(2007, 'P', '', '', 'Also, explain the labels on the x-axis. This functional form is called a <i>Gaussian form</i>.', 1, 'Warm-up01');
INSERT INTO webct VALUES(2008, 'P', '', '', 'Plotting is easy in MATLAB for both real and complex numbers. The basic <tt>plot</tt> command will plot a vector <tt>y</tt> versus a vector <tt>x</tt>. Try the following: <pre>x = [-3 -1 0 1 3 ];<p>y = x.*x - 3*x;<p>plot( x, y )<p>z = x + y*sqrt(-1)<p>plot( z ) <span class="ML_comment">%<-- complex values: plot imag vs. real</span></pre>Use <tt>help arith</tt> to learn how the operation <tt>xx.*xx</tt> works when <tt>xx</tt> is a vector; compare array multiplication (dot-star) to matrix multiplication.<div class="center"><span class="center lab_note">When unsure about a command, use <tt>help</tt>.</span></div>', 1, 'Warm-up01');
INSERT INTO webct VALUES(2009, 'P', '', '', 'Use the built-in MATLAB editor to create a script file called <tt>mylab1.m</tt> containing the following lines:<pre>tt = -1 : 0.01 : 1;<p>xx = cos( 5*pi*tt );<p>zz = 1.4*exp(j*pi/2)*exp(j*5*pi*tt);<p>plot( tt, xx, \'b-\', tt, real(zz), \'r.-\' ), grid on <span class="ML_comment">%<-- plot a sinusoid</span><p>title(\'TEST PLOT of a SINUSOID\')<p>xlabel(\'TIME (sec)\')</pre>Note: <i>Do not save</i> this file or any of your MATLAB files to the local hard disk. Your computer account contains a private networked directory where you can store your own files. Use the MATLAB command <tt>addpath()</tt> to allow MATLAB to "see" your personal directory (usually the Z: drive).<p>Use Euler''s formula, <tt>e<sup>j&omega;t</sup>=cos(&omega;t)+jsin(&omega;t)</tt>, to explain why the plot of <tt>real(zz)</tt> is a sinusoid.', 1, 'Warm-up01');
INSERT INTO webct VALUES(2010, 'P', '', '', 'Make a calculation of the phase from a time-shift measured on the plot.<p>What is its phase and amplitude?', 2, 'Warm-up01');
INSERT INTO webct VALUES(2011, 'P', '', '', 'Run your script from MATLAB. To run the file <tt>mylab1</tt> that you created previously, try <pre>mylab1 <span class="ML_comment">     %<-- will run the commands in the file</span><p>type mylab1 <span class="ML_comment">%<-- will type out the contents of mylab1.m<p>            %    to the screen</span></pre>', 0, 'Warm-up01');