# Lab 6: Warm-up Questions
# Insert into webct table
# id | qtype | title | image | question | answers | category
INSERT INTO webct VALUES(2040,'P','Synthesize a Test Image','','Generate a simple test image in which all of the columns are identical by using the following <i>outer product</i>:<pre>xpix = ones(256,1)*cos(2*pi*(0:255)/16);</pre>', 0, 'Warm-up06');
INSERT INTO webct VALUES(2041,'P','Synthesize a Test Image','','Display the image and explain the gray-scale pattern that you see.', 1, 'Warm-up06');
INSERT INTO webct VALUES(2042,'P','Synthesize a Test Image','','How wide are the bands in number of pixels?', 1, 'Warm-up06');
INSERT INTO webct VALUES(2043,'P','Synthesize a Test Image','','How can you predict that width from the formula for <tt>xpix</tt>?', 1, 'Warm-up06');
INSERT INTO webct VALUES(2044,'P','Synthesize a Test Image','','In the previous part, which data value in <tt>xpix</tt> is represented by white? which one by black?', 1, 'Warm-up06');
INSERT INTO webct VALUES(2045,'P','Synthesize a Test Image','','<i>Optional:</i> Explain how you would produce an image with bands that are horizontal. Give the formula that would create a 400 x 400 image with five horizontal black bands separated by white bands. Write the MATLAB code to make this image and display it.',1,'Warm-up06');
INSERT INTO webct VALUES(2046,'P','Aliasing in a Test Image','','Generate two test images with different frequencies, one with <tt>wd = 2*pi*1/16</tt> and the other with <tt>wd = 2*pi*7/16</tt>. Display the images, and explain why the image from the higher frequency has a shorter horizontal period.',1,'Warm-up06');
INSERT INTO webct VALUES(2047,'P','Aliasing in a Test Image','','Now we apply downsampling by two, i.e., <tt>xpix(1:2:end,1:2:end)</tt>, to both images from the previous part. Use <tt>subplot(2,2,n)</tt> to put these two images in the same figure window with the two images generated in part (a). Explain why the two downsampled images look the same.',1,'Warm-up06');
INSERT INTO webct VALUES(2048,'P','Sample an Image','','Read in the <tt>lighthouse.png</tt> file with the MATLAB function <tt>imread</tt>. When you check the size of the image, you&rsquo;ll find that it is not square. Now down-sample the <tt>lighthouse</tt> image<sup><span class="footer" onmouseover="footer(this,\'Definition: &pi;=1\',1)" onmouseout="footer(this,\'\',0)">10</span></sup> by a factor of 2. What is the size of the down-sampled image?',1,'Warm-up06');
INSERT INTO webct VALUES(2049,'P','Image Aliasing','','Notice the aliasing in the down-sampled image, which is surprising since no new values are being created by the down-sampling process. Describe how the aliasing appears visually. <sup><span class="footer" onmouseover="footer(this,\'One difficulty with showing aliasing is that we must display the pixels of the image exactly. This almost never happens because most monitors and printers will perform some sort of interpolation to adjust the size of the image to match the resolution of the device. In MATLAB we can override these size changes by using the function <tt>truesize</tt> which is part of the Image Processing Toolbox. In the <i>SP-First</i> toolbox, an equivalent function called <tt>trusize.m</tt> is provided.\',1)" onmouseout="footer(this,\'\',0)">11</span></sup> Which parts of the image show the aliasing effects most dramatically? Explain why the aliasing is happening by thinking about high frequencies in the image, i.e., look for features in the images that are periodic and can be described as having a frequency.',1,'Warm-up06');