# Lab 8: Warm-up Questions
# Insert into webct table
# id | qtype | title | image | question | answers | category
INSERT INTO webct VALUES(2062,'P','LTI Frequency Response Demo','','Set the input to <tt>x[n] = 3.6 cos(0.1&pi; (n-6))</tt> note that this sinusoid has a peak at <tt>n=6</tt>.', 0, 'Warm-up08');
INSERT INTO webct VALUES(2063,'P','LTI Frequency Response Demo','','Set the digital filter to be a 9-point averager.', 0, 'Warm-up08');
INSERT INTO webct VALUES(2064,'P','LTI Frequency Response Demo','',' Determine the formula for the output signal and write it in the form: <tt>y[n] = A cos(<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"><sub>0</sub>(n-n<sub>d</sub>))</tt>', 1, 'Warm-up08');
INSERT INTO webct VALUES(2065,'P','LTI Frequency Response Demo','','Using <tt>n<sub>d</sub></tt> from <tt>y[n]</tt> and the fact that the input signal had a peak at <tt>n=6</tt>, determine how much the peak of the cosine wave has shifted.  This is called the <i>delay</i> through the filter. Give an equation that explains how the delay is related to the phase of <tt>H(e<sup>j<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></sup>)</tt> at <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = 0.1&pi;</tt>.', 1, 'Warm-up08');
INSERT INTO webct VALUES(2066,'P','LTI Frequency Response Demo','','Now, change the length of the averaging filter so that the output will be zero, i.e., <tt>y[n] = 0</tt>. Use the GUI to show that you have the correct filter to zero the output.  If the filter length is more than 15, you will have to enter the &ldquo;Filter Specifications&rdquo; with the <span class="box"><tt>user Input</tt></span> option.<p><i>Hint:</i> Recall the Dirichlet form for the frequency response of the averaging filter, and where it is zero.<p>What is the length <b>L</b> of running average FIR filter that nulls <tt>x[n] = 3.6 cos(0.1&pi;(n-6))</tt>?', 1, 'Warm-up08');
INSERT INTO webct VALUES(2067,'P','LTI Frequency Response Demo','','When the output is zero, the filter acts as a <i>Nulling Filter</i>, because it eliminates the input at <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> =  0.1&pi;</tt>. Sinusoidal components at other frequencies <img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> will also be nulled &mdash; make a list of these frequencies.', 1, 'Warm-up08');
INSERT INTO webct VALUES(2068,'P','Ideal Filters and Practical Filters','','Define the input to be <tt>x[n] = 3.6 cos(0.55&pi; n)</tt>.', 0, 'Warm-up08');
INSERT INTO webct VALUES(2069,'P','Ideal Filters and Practical Filters','','Set the filter to be an ideal HPF with a cutoff frequency of <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"><sub>c</sub> = 2&pi;(0.2)</tt>. Determine a value for the phase slope so that the output will be <tt>y[n] = 3.6 cos(0.55&pi; n - 1.1&pi;)</tt>.', 1, 'Warm-up08');
INSERT INTO webct VALUES(2070,'P','Ideal Filters and Practical Filters','','Still using the ideal HPF selection, determine a cutoff frequency <tt>(<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"><sub>c</sub>)</tt> so that the output will be zero; the answer is not unique.', 1, 'Warm-up08');
INSERT INTO webct VALUES(2071,'P','Ideal Filters and Practical Filters','','Now switch to the length&minus;15 HPF, using the same input signal. Determine a formula for the output signal when the cutoff frequency is <tt>2&pi;(0.2)</tt>.  Is the signal still <i>passed</i> by the HPF?', 1, 'Warm-up08');
INSERT INTO webct VALUES(2072,'P','Ideal Filters and Practical Filters','','Again with the length&minus;15 HPF, use the cutoff frequency <tt>(<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"><sub>c</sub>)</tt> from part (c) and determine the formula for the output signal. Why is the  output not exactly zero?', 1, 'Warm-up08');
INSERT INTO webct VALUES(2073,'P','Ideal Filters and Practical Filters','','Determine a cutoff frequency for the length&minus;15 HPF so that the output signal is very close to zero. Give the formula for the output signal, and compare the cutoff frequency <tt>(<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"><sub>c</sub>)</tt> to part (c).', 1, 'Warm-up08');