# Lab 12: Warm-up Questions
# Insert into webct table
# id | qtype | title | image | question | answers | category
INSERT INTO webct VALUES(2101,'P','','','State the property of the polynomial coefficients of <tt>A(z) = 1 - a<sub>1</sub>z<sup>-1</sup> - a<sub>2</sub>z<sup>-2</sup></tt> that will guarantee that the two roots of <tt>A(z)</tt> are either both real, or are complex conjugates of each other.', 1, 'Warm-up12');
INSERT INTO webct VALUES(2102,'P','','','Clear all the poles and zeros from <b>PeZ</b>, using the <span class="ITS_box"><tt>-A</tt></span> button. Now place a pole pair that makes the following denominator polynomial for <tt>H(z)</tt>: <tt>1 + 0.9z<sup>-1</sup> + 0.81z<sup>-2</sup></tt>, and two zeros to make the numerator <tt>1-z<sup>-2</sup></tt>. Determine the radius and angles of the poles by factoring. The frequency response has a peak&ndash;record the frequency (location) of this peak.', 1, 'Warm-up12');
INSERT INTO webct VALUES(2103,'P','','','Change the angle of the pole and observe <tt>H(e<sup>j<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></sup>)</tt>: move the pole-pair angles to <tt>(&plusmn; 90&deg;)</tt>, then to <tt>(&plusmn; 60&deg;)</tt> and <tt>(&plusmn; 45&deg;)</tt>. Describe the changes in <tt>|H(e<sup>j&omega;</sup>)|</tt>. Concentrate on the height and location of the peak versus frequency <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></tt>.', 1, 'Warm-up12');
INSERT INTO webct VALUES(2104,'P','','','Start again with the poles and zeros from part (b). Decrease the radial distance of the poles (from the origin) by dragging, and observe how <tt>|H(e<sup>j<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></sup>)|</tt> changes. Even though dragging is imprecise because it&rsquo;s hard to stay on a constant angle, it is a very  informative way to discover the changes in <tt>|H(e<sup>j<img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></sup>)|</tt> as you reduce the pole radius.', 1, 'Warm-up12');
INSERT INTO webct VALUES(2105,'P','','','Increase the radius of the poles by pushing them closer to the unit circle, and  then move the poles outside the unit circle. When the pole-pair is outside the unit circle, describe what happens to <tt>h[n]</tt>.', 1, 'Warm-up12');
INSERT INTO webct VALUES(2106,'P','','','To test your understanding of sampling as well as digital filtering, design a BPF whose passband is centered at <tt>7300</tt> Hz when the sampling rate is <tt>22050</tt> Hz using a two-pole IIR filter as in part (b), i.e., determine a value of <tt>r</tt>, and the angles of the poles. As a reminder, you are designing a digital filter to be used  as the system <tt>H(z)</tt> in Fig. 2.<center><p><img src="images/C2D_Hz_D2C_probs.png"><br>Figure 2: Filtering the analog signal <tt>x(t)</tt> with a digital filter.</center>', 1, 'Warm-up12');
INSERT INTO webct VALUES(2107,'P','','','Clear all the poles and zeros  from <b>PeZ</b>. Then start again with the  <i>poles only</i> from part (b), and place two zeros exactly on the unit circle at the same angles as the poles.  You will have to calculate the zeros, and then use the <span class="ITS_box"><tt>Zero Location</tt></span> edit window to enter the exact values. Judging from the frequency response what type of filter have you just implemented? Is the system IIR or FIR?', 1, 'Warm-up12');
INSERT INTO webct VALUES(2108,'P','','','Write out the expression for <tt>H(z)</tt> created in part (g). Even though the GUI provides <tt>H(z)</tt>, you should create <tt>H(z)</tt> by multiplying out first-order terms with the poles and zeros, see <span class="footer" onmouseover="footer(this,\'<div class=center><table class=ITS_Equation><tr><td style=width:90%><img src=/ece2025/cgi-bin/mimetex.exe?H(z)=\\\\frac{B(z)}{A(z)}=G\\\\;\\\\frac{\\\\prod_{k=1}^M(1-z_k{z^{-1}})}{\\\\prod_{\\\\ell=1}^N(1-p_\\\\ell{z^{-1}})}=\\\\frac{\\\\sum_{k=0}^M{b_k}z^{-k}}{1-\\\\sum_{\\\\ell=1}^N{a_\\\\ell}z^{-\\\\ell}}></td><td>(1)</td></tr></table></div>\',1)" onmouseout="footer(this,\'\',0)">eq. (1)</span>.', 1, 'Warm-up12');
INSERT INTO webct VALUES(2109,'P','','','Once again start again with the <i>poles only</i> from part (b). Now place zeros at the conjugate-inverse locations <tt>1/p<sub>i<sup>*</sup></sub></tt>, where <tt>p<sub>i</sub></tt> are the poles. If you have the polar representation of the poles, it would be easy to get the polar representation of these complex-valued zeros. Judging from the frequency  response what type of filter have you just implemented?  Is the system  IIR or FIR?', 1, 'Warm-up12');
INSERT INTO webct VALUES(2110,'P','','','Write out the expression for <tt>H(z)</tt> created in part (i). Even though the GUI provides <tt>H(z)</tt>, you should do this from the given poles and zeros. <i>Hint:</i> use MATLAB&rsquo;s <tt>poly</tt> function, or <span class="footer" onmouseover="footer(this,\'<div class=center><table class=ITS_Equation><tr><td style=width:90%><img src=/ece2025/cgi-bin/mimetex.exe?H(z)=\\\\frac{B(z)}{A(z)}=G\\\\;\\\\frac{\\\\prod_{k=1}^M(1-z_k{z^{-1}})}{\\\\prod_{\\\\ell=1}^N(1-p_\\\\ell{z^{-1}})}=\\\\frac{\\\\sum_{k=0}^M{b_k}z^{-k}}{1-\\\\sum_{\\\\ell=1}^N{a_\\\\ell}z^{-\\\\ell}}></td><td>(1)</td></tr></table></div>\',1)" onmouseout="footer(this,\'\',0)">eq. (1)</span>.', 1, 'Warm-up12');