CREATE TABLE webct(
    id              int UNIQUE,
    qtype           varchar(2),
    title     		varchar(128),
    image  			varchar(32),
    question        varchar(2048),
    answers         int,
    category        varchar(16),

    PRIMARY KEY (id)
);
#----------------------------------------
CREATE TABLE webct_s(
    id          int,
    ans1        varchar(512),
		ans2		varchar(512),
    ans3        varchar(512),
		ans4		varchar(512),
    ans5        varchar(512),
		ans6		varchar(512),
    ans7        varchar(512),
		ans8		varchar(512),
    ans9        varchar(512),
		ans10		varchar(512),
    ans11       varchar(512),
		ans12		varchar(512),
		
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES webct (id) ON DELETE CASCADE
);
#----------------------------------------
CREATE TABLE webct_mc(
    id              int,
    feedback      	varchar(32),
    weight1   		int,
    answer1     	varchar(512),
    reason1         varchar(512),
    weight2   		int,
    answer2     	varchar(512),
    reason2         varchar(512),
    weight3   		int,
    answer3     	varchar(512),
    reason3         varchar(512),
    weight4   		int,
    answer4     	varchar(512),
    reason4         varchar(512),
    weight5   		int,
    answer5     	varchar(512),
    reason5         varchar(512),
    weight6  		int,
    answer6     	varchar(512),
    reason6         varchar(512),
    weight7   		int,
    answer7     	varchar(512),
    reason7         varchar(512),
    weight8   		int,
    answer8     	varchar(512),
    reason8         varchar(512),
    weight9   		int,
    answer9     	varchar(512),
    reason9         varchar(512),
    weight10   		int,
    answer10     	varchar(512),
    reason10        varchar(512),
    weight11   		int,
    answer11     	varchar(512),
    reason11        varchar(512),
    weight12   		int,
    answer12     	varchar(512),
    reason12        varchar(512),
    weight13   		int,
    answer13     	varchar(512),
    reason13        varchar(512),
    weight14   		int,
    answer14     	varchar(512),
    reason14        varchar(512),
    weight15   		int,
    answer15     	varchar(512),
    reason15        varchar(512),
    weight16  		int,
    answer16     	varchar(512),
    reason16        varchar(512),
    weight17   		int,
    answer17     	varchar(512),
    reason17        varchar(512),
    weight18   		int,
    answer18     	varchar(512),
    reason18        varchar(512),
    weight19   		int,
    answer19     	varchar(512),
    reason19        varchar(512),
    weight20   		int,
    answer20     	varchar(512),
    reason20        varchar(512),
    weight21   		int,
    answer21     	varchar(512),
    reason21        varchar(512),
    weight22   		int,
    answer22     	varchar(512),
    reason22        varchar(512),

    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES webct (id) ON DELETE CASCADE
);
#----------------------------------------
CREATE TABLE webct_p( 
		id          int,
    template  	varchar(256),
    answer   		varchar(2048),
    
    PRIMARY KEY (id),
		FOREIGN KEY (id) REFERENCES webct (id) ON DELETE CASCADE
);
#----------------------------------------
CREATE TABLE webct_m(
    id         			int,
    L1 					varchar(256),
    R1     				varchar(256),
    L2 					varchar(256),
    R2     				varchar(256),
    L3 					varchar(256),
    R3     				varchar(256),
    L4 					varchar(256),
    R4     				varchar(256),
    L5 					varchar(256),
    R5     				varchar(256),
    L6 					varchar(256),
    R6     				varchar(256),
    L7 					varchar(256),
    R7     				varchar(256),
    L8 					varchar(256),
    R8     				varchar(256),
    L9 					varchar(256),
    R9     				varchar(256),
    L10 				varchar(256),
    R10     			varchar(256),
    L11 				varchar(256),
    R11     			varchar(256),
    L12 				varchar(256),
    R12     			varchar(256),
    L13 				varchar(256),
    R13     			varchar(256),
    L14 				varchar(256),
    R14     			varchar(256),
    L15 				varchar(256),
    R15     			varchar(256),
    L16 				varchar(256),
    R16     			varchar(256),
    L17 				varchar(256),
    R17     			varchar(256),
    L18 				varchar(256),
    R18     			varchar(256),
    L19 				varchar(256),
    R19     			varchar(256),
    L20 				varchar(256),
    R20     			varchar(256),
    L21 				varchar(256),
    R21     			varchar(256),
    L22 				varchar(256),
    R22     			varchar(256),
    L23 				varchar(256),
    R23     			varchar(256),
    L24 				varchar(256),
    R24     			varchar(256),
    L25 				varchar(256),
    R25     			varchar(256),
    L26 				varchar(256),
    R26     			varchar(256),
    L27 				varchar(256),
    R27     			varchar(256),
    
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES webct (id) ON DELETE CASCADE
);
#----------------------------------------
CREATE TABLE webct_c(
    id         			int,
    formula    			varchar(256),
    val1     	 		varchar(8),
    min_val1            int,
    max_val1            int,
    val2     	 		varchar(8),
    min_val2            int,
    max_val2            int,
    val3     	 		varchar(8),
    min_val3            int,
    max_val3            int,
    val4     	 		varchar(8),
    min_val4            int,
    max_val4            int,
    val5     	 		varchar(8),
    min_val5            int,
    max_val5            int,
    val6     	 		varchar(8),
    min_val6            int,
    max_val6            int,
    val7     	 		varchar(8),
    min_val7            int,
    max_val7            int,
    val8     	 		varchar(8),
    min_val8            int,
    max_val8            int,
    val9     	 		varchar(8),
    min_val9            int,
    max_val9            int,
    val10     	 		varchar(8),
    min_val10           int,
    max_val10           int,
	vals                int,
    
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES webct (id) ON DELETE CASCADE
);
#----------------------------------------