# Pre-Lab 6: Questions
# id | qtype | title | image | question | answers | category
INSERT INTO webct VALUES(1203,'MC','Sampling theorem','','Set the input frequency to <tt>&fnof;<sub>0</sub> = 13.4</tt> Hz. Determine the smallest <font color="darkgreen">integer</font> value of the sampling rate <tt>&fnof;s</tt> so that no aliasing occurs.  The units of <tt>&fnof;<sub>s</sub></tt> are samples per second.  You must justify your response by citing a theorem or property about sampling.', 4, 'lab5');
INSERT INTO webct VALUES(1204,'MC','','','Set the input frequency to <tt>&fnof;<sub>0</sub> = 13</tt> Hz and the input phase to <tt>&phi; = -1.3</tt> rads. Determine the locations of the spectral lines in the spectrum of the discrete-time signal (middle plot of the bottom row) when the sampling rate  is <tt>&fnof;s = 29</tt> Hz.  Calculate <img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> for the two spectral lines that lie in the range <tt>-&pi; &le; <img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> &le; &pi;</tt>. Explain how you calculated the two values for <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></tt>, i.e., give the formula for <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"></tt> in terms of <tt>&fnof;<sub>0</sub></tt> and <tt>&fnof;<sub>s</sub></tt>.', 4, 'lab5');
INSERT INTO webct VALUES(1205,'MC','','','<i>Folded Alias:</i> Set the input frequency to <tt>&fnof;<sub>0</sub> = 13</tt> Hz, the input phase to <tt>&phi; = -1.3</tt> rads, and <tt>&fnof;<sub>s</sub> = 20</tt> Hz. Write down the formula for the output signal, and then write a justification consisting of three steps:<OL><LI>calculating the values of <img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> for the blue spectral lines in the spectrum of the discrete-time signal <tt>x[n]</tt> shown in the middle plots,<LI>aliasing <img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> (blue to red), and<LI>transforming <tt>x[n]</tt> into <tt>y(t)</tt> using an equation that describes the ideal D-to-C converter and uses the <i>principal aias</i>.</OL> ', 5, 'lab5');
INSERT INTO webct VALUES(1206,'MC','','','Set the sampling rate to frequency to <tt>&fnof;<sub>s</sub> = 23</tt> Hz, and assume that the output signal has a frequency of <tt>9</tt> Hz, and a phase of <tt>+1.3</tt>. Determine <b>ONE</b> ( <tt>&fnof;<sub>0</sub></tt> , &phi; ) pair value that will give this output signal. Assume that the amplitude is one.', 5, 'lab5');
INSERT INTO webct VALUES(1207,'MC','','','Set the input frequency to <tt>&fnof;<sub>0</sub> = 13</tt> Hz and the input phase to <tt>&phi; = -1.3</tt> rads. Determine the <b>sampling rate</b> <tt>&fnof;<sub>s</sub></tt> so that the output signal has a frequency of <tt>9</tt> Hz, and a phase of <tt>+1.3</tt> rads. Trial and error helps in getting the answer, but you must write an explanation based on theory.', 5, 'lab5');

# Insert into webct table
# id | feedback | weight{n} | answer{n} | reason{
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4) VALUES(1203,0,'<tt>&fnof;<sub>s</sub> = 7 Hz</tt>',100,'<tt>&fnof;<sub>s</sub> = 27 Hz</tt>',0,'<tt>&fnof;<sub>s</sub> = 14 Hz</tt>',0,'<tt>&fnof;<sub>s</sub> = 20 Hz</tt>');
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4) VALUES(1204,0,'<tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 0.103&pi;</tt>',0,'<tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 0.569&pi;</tt>',100,'<tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 0.897&pi;</tt>',0,'<tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 1.103&pi;</tt>');
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4,weight5,answer5) VALUES(1205,100,'principal alias at <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 0.7&pi;</tt>',0,'principal alias at <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 1.3&pi;</tt>',0,'principal alias at <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 0.8&pi;</tt>',0,'principal alias at <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 1.7&pi;</tt>',0,'principal alias at <tt><img src="/ece2025/cgi-bin/mimetex.exe?\\hat\\omega"> = &plusmn; 1.6&pi;</tt>');
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4,weight5,answer5) VALUES(1206,0,'<tt>&fnof;<sub>0</sub> = 32 Hz, &phi; = -1.3</tt>',100,'<tt>&fnof;<sub>0</sub> = 23 Hz, &phi; = -1.3</tt>',0,'<tt>&fnof;<sub>0</sub> = 14 Hz, &phi; = 1.3</tt>',0,'<tt>&fnof;<sub>0</sub> = 14 Hz, &phi; = -1.3</tt>',0,'<tt>&fnof;<sub>0</sub> = 9 Hz, &phi; = 0</tt>');
INSERT INTO webct_mc (id,weight1,answer1,weight2,answer2,weight3,answer3,weight4,answer4,weight5,answer5) VALUES(1207,0,'<tt>&fnof;<sub>s</sub> = 9 Hz</tt>',0,'<tt>&fnof;<sub>s</sub> = 13 Hz</tt>',0,'<tt>&fnof;<sub>s</sub> = 22 Hz</tt>',100,'<tt>&fnof;<sub>s</sub> = 35 Hz</tt>',0,'none of the above');